name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]   # ajusta si usas otra rama
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"      # carpeta donde está index.html
          api_location: ""       # sin API
          output_location: ""    # sin build
          skip_app_build: true   # HTML plano
