- name: Build And Deploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    repo_token: ${{ secrets.GITHUB_TOKEN }}
    action: "upload"
    app_location: "/"        # carpeta donde está index.html
    api_location: ""         # sin API
    output_location: ""      # vacío porque no hay paso de build
    skip_app_build: true     # clave para HTML plano
